/**
 * Core types for @canopy/item-store.  jsdoc only (no TypeScript).
 *
 * Item shape is the SUPERSET of what H2 (household items) and H4
 * (tasks) need.  H2-only consumers leave H4-extension fields
 * (`dependencies`, `requiredSkills`, `assignee`, etc.) absent;
 * substrate doesn't enforce their presence.
 */

/**
 * @typedef {object} Item
 *
 * @property {string} id
 *   ULID — generated by the substrate on add.  Lexicographically
 *   sortable by creation time.
 *
 * @property {string} type
 *   App-defined.  H2: 'shopping' | 'errand' | 'repair' | 'schedule'.
 *   H4: 'task' or any app-defined string.  Substrate doesn't validate
 *   the enum — apps own their type vocabulary.
 *
 * @property {string} text
 *   Primary content (item title or task name).
 *
 * @property {string} [notes]
 *   Optional longer-form description.
 *
 * @property {string} addedBy
 *   Webid of the actor who added the item.  Required.
 *
 * @property {string} [addedByDisplayName]
 *   Snapshot of the display name at write time.  Survives if the
 *   member leaves the household and their webid becomes
 *   unresolvable.  Optional but strongly recommended for
 *   attribution rendering.
 *
 * @property {number} addedAt
 *   ms epoch.  Set by the substrate on add.
 *
 * @property {number} [completedAt]
 *   ms epoch when the item was marked complete.  Absent if open.
 *
 * @property {string} [completedBy]
 *   Webid of the actor who marked complete.  Absent if open.
 *
 * @property {string} [completedByDisplayName]
 *   Snapshot, same rationale as addedByDisplayName.
 *
 * @property {Array<string>} [dependencies]
 *   H4-extension: ids of items this one depends on.  Open items with
 *   incomplete dependencies are computed `status: waiting`.
 *
 * @property {Array<string>} [requiredSkills]
 *   H4-extension: skill tags consumed by L1e (skill-match) for
 *   matchmaking + claim flow.
 *
 * @property {number} [dueAt]
 *   ms epoch.  Optional deadline.  Used by L1f (notifier) for
 *   deadline reminders.
 *
 * @property {string} [assignee]
 *   Webid.  H4-extension.  Mutated only via `claim` (CAS) or
 *   `reassign` (role-policy-gated).
 *
 * @property {number} [claimedAt]
 *   ms epoch when the assignee was set.
 *
 * @property {Visibility} [visibility]
 *   H4-extension.  Default: 'household'.  Filtered on read by the
 *   role-policy gate (when configured).
 *
 * @property {object} [source]
 *   App-specific opaque metadata.  H2 uses this for chat-source
 *   tracking ({tg: {chatId, messageId}}); other apps may not need it.
 *
 * @property {string} [_etag]
 *   Per-item version tag for optimistic concurrency.  Substrate sets
 *   on every write; consumers pass it back on `update` for CAS.
 */

/**
 * @typedef {'household' | `role:${string}` | 'private'} Visibility
 */

/**
 * @typedef {object} ListFilter
 *
 * @property {string | string[]} [type]
 *   Single type or list.
 *
 * @property {string | null} [assignee]
 *   Webid filter.  `null` means "unassigned only".
 *
 * @property {string} [requiredSkill]
 *   Match items whose `requiredSkills` includes this skill.
 *
 * @property {Visibility} [visibility]
 *   Match items with this visibility tag.  When the role-policy
 *   gate is configured, results are also filtered by what the
 *   actor is allowed to see.
 *
 * @property {number} [since]
 *   ms epoch.  Match items with `addedAt >= since`.
 */

/**
 * @typedef {object} ActorContext
 *
 * @property {string} actor
 *   Webid of the actor performing the action.  Used by audit log +
 *   role-policy gate.
 *
 * @property {string} [actorDisplayName]
 *   Snapshot to write into the item's `addedByDisplayName` /
 *   `completedByDisplayName` etc.  Optional; if absent, only the
 *   webid is recorded.
 */

/**
 * @typedef {object} ItemRef
 *
 * Reference to an item by id or fuzzy text match.  Used by
 * `markComplete` and `removeItems` to support both precise references
 * (preferred — id) and conversational references ("appels en melk").
 *
 * @property {string} [id]
 * @property {string} [match]
 */

/**
 * @typedef {object} AuditEntry
 *
 * @property {string} id
 *   ULID for the audit entry.
 *
 * @property {string} itemId
 *
 * @property {AuditAction} action
 *
 * @property {string} actor
 *
 * @property {string} [actorDisplayName]
 *
 * @property {number} at
 *   ms epoch.
 *
 * @property {object} [details]
 *   Action-specific extra data.  E.g. for 'reassign': {from, to}.
 */

/**
 * @typedef {'add' | 'complete' | 'remove' | 'claim' | 'reassign' | 'update'} AuditAction
 */

/**
 * Pluggable role-policy gate.  Substrate ships a no-op default
 * (everything allowed).  Apps that need RBAC inject their own
 * implementation — e.g. H4 ships the standard 5-role permission
 * table.
 *
 * Each method returns true if the action is allowed; false to
 * forbid.  The substrate translates `false` into a thrown
 * `PermissionDeniedError`.
 *
 * @typedef {object} RolePolicy
 *
 * @property {(actor: string, item: Partial<Item>) => boolean} [canAdd]
 * @property {(actor: string, item: Item) => boolean}          [canComplete]
 * @property {(actor: string, item: Item) => boolean}          [canRemove]
 * @property {(actor: string, item: Item) => boolean}          [canClaim]
 * @property {(actor: string, item: Item) => boolean}          [canReassign]
 * @property {(actor: string, item: Item, patch: Partial<Item>) => boolean} [canEditBody]
 * @property {(actor: string, item: Item) => boolean}          [canRead]
 */

/**
 * Backend interface — what the substrate's high-level API uses
 * underneath.  Apps usually consume the high-level API; the backend
 * is for internal substrate code + when an app needs custom storage
 * (e.g. pod-backed via PodClient when L1b ships its PodBackend).
 *
 * @typedef {object} Backend
 *
 * @property {(item: Item) => Promise<Item>} putItem
 *   Idempotent write.  Backend should detect concurrent writes via
 *   `_etag` and reject mismatches.
 *
 * @property {(id: string) => Promise<Item|null>} getItem
 *
 * @property {(filter: ListFilter & {includeClosed?: boolean}) => Promise<Item[]>} listItems
 *
 * @property {(id: string) => Promise<void>} deleteItem
 *   Hard delete.  No tombstone — substrate's `removeItems` is the
 *   user-facing primitive.
 *
 * @property {(entry: AuditEntry) => Promise<void>} appendAudit
 *
 * @property {(filter?: AuditFilter) => Promise<AuditEntry[]>} listAudit
 */

/**
 * @typedef {object} AuditFilter
 * @property {string} [itemId]
 * @property {string} [actor]
 * @property {AuditAction} [action]
 * @property {number} [since]
 * @property {number} [until]
 */

// Empty export so this file is a real ES module.
export const __types__ = true;
