/**
 * Core types for @canopy/item-store.  jsdoc only (no TypeScript).
 *
 * Item shape is the SUPERSET of what H2 (household items) and H4
 * (tasks) need.  H2-only consumers leave H4-extension fields
 * (`dependencies`, `requiredSkills`, `assignee`, etc.) absent;
 * substrate doesn't enforce their presence.
 */

/**
 * @typedef {object} Item
 *
 * @property {string} id
 *   ULID — generated by the substrate on add.  Lexicographically
 *   sortable by creation time.
 *
 * @property {string} type
 *   App-defined.  H2: 'shopping' | 'errand' | 'repair' | 'schedule'.
 *   H4: 'task' or any app-defined string.  Substrate doesn't validate
 *   the enum — apps own their type vocabulary.
 *
 * @property {string} text
 *   Primary content (item title or task name).
 *
 * @property {string} [notes]
 *   Optional longer-form description.
 *
 * @property {string} addedBy
 *   Webid of the actor who added the item.  Required.
 *
 * @property {string} [addedByDisplayName]
 *   Snapshot of the display name at write time.  Survives if the
 *   member leaves the household and their webid becomes
 *   unresolvable.  Optional but strongly recommended for
 *   attribution rendering.
 *
 * @property {number} addedAt
 *   ms epoch.  Set by the substrate on add.
 *
 * @property {number} [completedAt]
 *   ms epoch when the item was marked complete.  Absent if open.
 *
 * @property {string} [completedBy]
 *   Webid of the actor who marked complete.  Absent if open.
 *
 * @property {string} [completedByDisplayName]
 *   Snapshot, same rationale as addedByDisplayName.
 *
 * @property {Array<string>} [dependencies]
 *   H4-extension: ids of items this one depends on.  Open items with
 *   incomplete dependencies are computed `status: waiting`.
 *
 * @property {Array<string>} [requiredSkills]
 *   H4-extension: skill tags consumed by L1e (skill-match) for
 *   matchmaking + claim flow.
 *
 * @property {number} [dueAt]
 *   ms epoch.  Optional deadline.  Used by L1f (notifier) for
 *   deadline reminders.
 *
 * @property {string} [assignee]
 *   Webid.  H4-extension.  Mutated only via `claim` (CAS) or
 *   `reassign` (role-policy-gated).
 *
 * @property {number} [claimedAt]
 *   ms epoch when the assignee was set.
 *
 * @property {Visibility} [visibility]
 *   H4-extension.  Default: 'household'.  Filtered on read by the
 *   role-policy gate (when configured).
 *
 *   **Legacy as of SP-5b V0a (2026-05-21).**  Superseded by
 *   `audience` (see below).  Items with only `visibility` keep
 *   working via the `audienceFromItem(item)` bridge helper.  New
 *   items should prefer the richer `audience` field.
 *
 * @property {Audience} [audience]
 *   SP-5b V0a (2026-05-21).  The audience a item is shared with.
 *   Strictly richer than `visibility`: accepts arbitrary
 *   `circle-ref` / `union` / `set` audiences in addition to the
 *   legacy string short-hands (`'household'`, `'private'`,
 *   `'role:*'`).
 *
 *   Forward-additive: items without `audience` fall back to
 *   `visibility` (substrate default `'household'`) via the
 *   `audienceFromItem(item)` helper.  Consumers should use the
 *   helper rather than reading either field directly.
 *
 *   Audience resolution (string short-hands → member-sets,
 *   circle-ref walks) lives in `@canopy/circles`'s
 *   `resolveAudience(audience, ctx)`.  Item-store stores the
 *   field as data; it does NOT resolve it.
 *
 * @property {object} [source]
 *   App-specific opaque metadata.  H2 uses this for chat-source
 *   tracking ({tg: {chatId, messageId}}); other apps may not need it.
 *
 * @property {string} [_etag]
 *   Per-item version tag for optimistic concurrency.  Substrate sets
 *   on every write; consumers pass it back on `update` for CAS.
 *
 * **DoD-lifecycle extension (Tasks V1, 2026-05-08):** the following
 * fields drive the optional submit/approve/reject/revoke flow.
 * Items written by V0 callers leave them all absent; their lifecycle
 * stays the legacy `open → claimed → complete` path.
 *
 * @property {string} [definitionOfDone]
 *   Free text (Markdown OK).  What "done" means for this item.
 *
 * @property {ApprovalMode} [approval]
 *   Default `'self-mark'` (legacy V0 behaviour: `markComplete` flips
 *   the item to complete).  `'creator'` requires the item author
 *   (`addedBy`) to approve a `submit`.  ``webid:`${string}` `` names a
 *   third-party approver.  Substrate stores the value verbatim and
 *   gates approve/reject on it.
 *
 * @property {Deliverable} [deliverable]
 *   Reference to the artifact submitted on `submit`.  Set by the
 *   substrate; carries `submittedAt`.
 *
 * @property {Array<ReviewLogEntry>} [reviewLog]
 *   Append-only log of submit / approve / reject / revoke decisions.
 *   The merge contract is append-only; new entries are concatenated
 *   in-place during the writing transition.
 *
 * @property {string} [master]
 *   Webid of the task's "master" — the actor allowed to revoke.
 *   Defaults to `addedBy` on add; defaults to the spawner on
 *   `addSubtask`.  Admins / coordinators bypass via the role policy.
 *
 * @property {string} [parentTaskId]
 *   When this item is a sub-task, the parent's id.  Apps maintain
 *   the parent's `dependencies` array in sync — adding a sub-task
 *   appends to the parent.
 */

/**
 * @typedef {'self-mark' | 'creator' | `webid:${string}`} ApprovalMode
 *
 * - `'self-mark'`: assignee marks complete via `markComplete`; same
 *   as V0.  No `submit`/`approve` needed.
 * - `'creator'`: the item's `addedBy` (or `master`) approves the
 *   submission.
 * - `'webid:<who>'`: a designated webid approves.
 */

/**
 * @typedef {object} Deliverable
 * @property {'pod-resource' | 'url' | 'note'} kind
 * @property {string} ref
 * @property {number} [submittedAt]
 */

/**
 * @typedef {object} ReviewLogEntry
 * @property {number} at
 * @property {string} by                                — webid
 * @property {'submit' | 'approve' | 'reject' | 'revoke'} decision
 * @property {string} [note]
 */

/**
 * @typedef {'household' | `role:${string}` | 'private'} Visibility
 *
 * **Legacy** as of SP-5b V0a (2026-05-21).  See `Audience` below for
 * the superseding field.
 */

/**
 * @typedef {string
 *   | { kind: 'set',         members: string[] }
 *   | { kind: 'circle-ref',  id: string }
 *   | { kind: 'union',       of: Audience[]    }
 *   | { kind: 'public' }
 * } Audience
 *
 * SP-5b V0a (2026-05-21).  Audience model — what set of webids an
 * item is shared with.  Mirrors `@canopy/circles`' Audience model;
 * defined as a typedef here so item-store can carry the field
 * without depending on the higher-level circles package.
 *
 * Recognised string short-hands (case-sensitive):
 *   'public'          — everyone (sentinel)
 *   'private' / 'me'  — owner only
 *   'household'       — household members (legacy Visibility's default)
 *   'role:NAME'       — actors in the named role
 *   'crew:ID'         — alias for circle-ref (per circle.id ≡ task.crewId)
 *   'circle:ID'       — circle-ref by id
 *
 * Resolution helpers (`normalizeAudience` / `resolveAudience` /
 * `inAudience`) live in `@canopy/circles`.  Item-store stores the
 * field verbatim; consumers resolve at read time.
 */

/**
 * @typedef {object} ListFilter
 *
 * @property {string | string[]} [type]
 *   Single type or list.
 *
 * @property {string | null} [assignee]
 *   Webid filter.  `null` means "unassigned only".
 *
 * @property {string} [requiredSkill]
 *   Match items whose `requiredSkills` includes this skill.
 *
 * @property {Visibility} [visibility]
 *   Match items with this visibility tag.  When the role-policy
 *   gate is configured, results are also filtered by what the
 *   actor is allowed to see.
 *
 * @property {Audience} [audience]
 *   SP-5b (2026-05-21).  Match items whose effective audience (via the
 *   `audienceFromItem` bridge — so legacy `visibility`-only items still
 *   match) satisfies this queried audience.
 *
 *   **Semantics** (see `audience.js#audienceMatches` for the full
 *   contract):
 *     1. **Exact match** — the item's effective audience structurally
 *        deep-equals the filter (key-order-independent).  Covers plain
 *        short-hands, `set`, `circle-ref`, `union`, `public`.
 *     2. **Union membership** — a `{kind:'union', of:[…]}` item matches
 *        when the filter satisfies ANY constituent (recursively).  So
 *        filtering by `{kind:'circle-ref', id:'c1'}` also returns items
 *        shared with `union(household, circle-ref c1)`.
 *     3. **Set membership** — a `{kind:'set', members:[…]}` item matches
 *        when the filter is a plain webid string in `members`.
 *
 *   Known limitation: the string short-hand `'crew:X'` and the
 *   structured form `{kind:'circle-ref', id:'X'}` are NOT considered
 *   equivalent (normalisation lives in `@canopy/circles`; item-store
 *   can't depend on it for layering reasons).  A future revision may
 *   lift `normalizeAudience` to item-types OR take a callback.
 *
 * @property {number} [since]
 *   ms epoch.  Match items with `addedAt >= since`.
 */

/**
 * @typedef {object} ActorContext
 *
 * @property {string} actor
 *   Webid of the actor performing the action.  Used by audit log +
 *   role-policy gate.
 *
 * @property {string} [actorDisplayName]
 *   Snapshot to write into the item's `addedByDisplayName` /
 *   `completedByDisplayName` etc.  Optional; if absent, only the
 *   webid is recorded.
 */

/**
 * @typedef {object} ItemRef
 *
 * Reference to an item by id or fuzzy text match.  Used by
 * `markComplete` and `removeItems` to support both precise references
 * (preferred — id) and conversational references ("appels en melk").
 *
 * @property {string} [id]
 * @property {string} [match]
 */

/**
 * @typedef {object} AuditEntry
 *
 * @property {string} id
 *   ULID for the audit entry.
 *
 * @property {string} itemId
 *
 * @property {AuditAction} action
 *
 * @property {string} actor
 *
 * @property {string} [actorDisplayName]
 *
 * @property {number} at
 *   ms epoch.
 *
 * @property {object} [details]
 *   Action-specific extra data.  E.g. for 'reassign': {from, to}.
 */

/**
 * @typedef {'add' | 'complete' | 'remove' | 'claim' | 'reassign' | 'update' | 'submit' | 'approve' | 'reject' | 'revoke'} AuditAction
 */

/**
 * Pluggable role-policy gate.  Substrate ships a no-op default
 * (everything allowed).  Apps that need RBAC inject their own
 * implementation — e.g. H4 ships the standard 5-role permission
 * table.
 *
 * Each method returns true if the action is allowed; false to
 * forbid.  The substrate translates `false` into a thrown
 * `PermissionDeniedError`.
 *
 * @typedef {object} RolePolicy
 *
 * @property {(actor: string, item: Partial<Item>) => boolean} [canAdd]
 * @property {(actor: string, item: Item) => boolean}          [canComplete]
 * @property {(actor: string, item: Item) => boolean}          [canRemove]
 * @property {(actor: string, item: Item) => boolean}          [canClaim]
 * @property {(actor: string, item: Item) => boolean}          [canReassign]
 * @property {(actor: string, item: Item, patch: Partial<Item>) => boolean} [canEditBody]
 * @property {(actor: string, item: Item) => boolean}          [canRead]
 * @property {(actor: string, item: Item) => boolean}          [canSubmit]
 *   DoD-lifecycle: who may transition `claimed → submitted`.
 *   Default: assignee.
 * @property {(actor: string, item: Item) => boolean}          [canApprove]
 *   DoD-lifecycle: who may transition `submitted → complete`.
 *   Default: the actor designated by `item.approval` ('creator' →
 *   `addedBy`/`master`; 'webid:X' → X).
 * @property {(actor: string, item: Item) => boolean}          [canReject]
 *   DoD-lifecycle: who may transition `submitted → rejected → claimed`.
 *   Default: same as canApprove.
 * @property {(actor: string, item: Item) => boolean}          [canRevoke]
 *   DoD-lifecycle: who may transition `claimed → open` (master-only,
 *   with mandatory reason).  Default: `master` or admin/coordinator.
 */

/**
 * Backend interface — what the substrate's high-level API uses
 * underneath.  Apps usually consume the high-level API; the backend
 * is for internal substrate code + when an app needs custom storage
 * (e.g. pod-backed via PodClient when L1b ships its PodBackend).
 *
 * @typedef {object} Backend
 *
 * @property {(item: Item) => Promise<Item>} putItem
 *   Idempotent write.  Backend should detect concurrent writes via
 *   `_etag` and reject mismatches.
 *
 * @property {(id: string) => Promise<Item|null>} getItem
 *
 * @property {(filter: ListFilter & {includeClosed?: boolean}) => Promise<Item[]>} listItems
 *
 * @property {(id: string) => Promise<void>} deleteItem
 *   Hard delete.  No tombstone — substrate's `removeItems` is the
 *   user-facing primitive.
 *
 * @property {(entry: AuditEntry) => Promise<void>} appendAudit
 *
 * @property {(filter?: AuditFilter) => Promise<AuditEntry[]>} listAudit
 */

/**
 * @typedef {object} AuditFilter
 * @property {string} [itemId]
 * @property {string} [actor]
 * @property {AuditAction} [action]
 * @property {number} [since]
 * @property {number} [until]
 */

// Empty export so this file is a real ES module.
export const __types__ = true;
